// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_vBwhzDq5GU87Yx8pgIiSLJ0dod8htg',
    appId: '1:325195656042:web:c9f615919f6bad6eef5313',
    messagingSenderId: '325195656042',
    projectId: 'mapmarking-2f3f7',
    authDomain: 'mapmarking-2f3f7.firebaseapp.com',
    storageBucket: 'mapmarking-2f3f7.appspot.com',
    measurementId: 'G-4VQ3VBLT1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hOJ7QME6-QHIsF6jdM0VFTQfWV4UeI8',
    appId: '1:325195656042:android:4b418974091023adef5313',
    messagingSenderId: '325195656042',
    projectId: 'mapmarking-2f3f7',
    storageBucket: 'mapmarking-2f3f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07Yp_FUeW47yi7bnYpquVMLF5axf4VBA',
    appId: '1:325195656042:ios:b01acf78ae751c35ef5313',
    messagingSenderId: '325195656042',
    projectId: 'mapmarking-2f3f7',
    storageBucket: 'mapmarking-2f3f7.appspot.com',
    iosBundleId: 'com.example.mapMarking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB07Yp_FUeW47yi7bnYpquVMLF5axf4VBA',
    appId: '1:325195656042:ios:b01acf78ae751c35ef5313',
    messagingSenderId: '325195656042',
    projectId: 'mapmarking-2f3f7',
    storageBucket: 'mapmarking-2f3f7.appspot.com',
    iosBundleId: 'com.example.mapMarking',
  );
}
